apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://127.0.0.1:50065
    certificate-authority-data: BASE64_ENCODED_CA_CERT
contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
current-context: minikube
users:
- name: minikube
  user:
    token: YOUR_AUTH_TOKEN
